### ISSUE TITLE
non-interactive mode possible?

### ISSUE THREAD

**Issue by draptik** [DEVDEER/dotnet-tocpm#14]
Thanks for sharing this useful tool!

Is it possible to run this tool in an non-interactive mode so it can be used by another script?
Using `--force` still waits for user input.

**Comment by devdeer-alex** [comment]
Someting like a `-Confirm` parameter?

**Comment by draptik** [comment]
sorry for the late reply.
Yes `-Confirm` would be fine! Although I would use `-noconfirm`, meaning that I don't want to confirm interactively.

**Comment by devdeer-alex** [comment]
I will do it

**Comment by devdeer-alex** [comment]
I just recognized that we already have a `-f` option doing that. I forgot about it. JJust use `tocpm execute . -f` to do that.
