### ISSUE TITLE
non-descript error when running comand

### ISSUE THREAD

**Issue by falvarez1** [DEVDEER/dotnet-tocpm#5]
I tried using the simulate attribute and received the following error:
![image](https://user-images.githubusercontent.com/23342133/213581066-74e9ee08-0d04-4087-b067-1c0b52871127.png)

The solution compiles fine and I'm unable to gather any more details regarding the error making troubleshooting difficult.  Any ideas?

**Comment by falvarez1** [comment]
Ok it looks like the issue with with Spectre Console treating text inside of brackets as [markup ](https://spectreconsole.net/markup)
I have PackageReferences that uses the bracket notation in the versions to represent packages that I do not want the NuGet package manager to flag as requiring updates (version constraining).  Here's an example:
![image](https://user-images.githubusercontent.com/23342133/213603435-1b8fc82e-ad19-4e57-9ff2-5295ecb92066.png)
I'm also testing with framework conditionals:
![image](https://user-images.githubusercontent.com/23342133/213610660-d1051953-04d1-45fe-9982-bd7c65d4e6cd.png)

**Comment by devdeer-alex** [comment]
@falvarez1 Thx for pointing this out. I'll try to adjust the regex expressions.

**Comment by devdeer-alex** [comment]
@falvarez1 Could you plz. provide some samples markdown-formatted in the comments here?
